sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: tb_user
    username: root
    password: password
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10

